/* Copyright 2018 Harry Boer - DappDevelopment.com
Licensed under the MIT License, see LICENCE file for details.
*/

/* Package pathdata contains the paths, addresses,
http:// addresses and seeds
*/
package metadata

//var Seed = "THISISTHETESTSENTENCETOEXPERIMENTWITHIOTATANGLEFORPROGRAMMINGUSECASESASWELLASFUN9"
var Seed = "BMYDBMQIKMPAVPY9CGQWSAQEVV9JAYDIZUOIWLQPGKLBIXEGY9S9BJBCQUSQODIYFUIEKPWAHUPNXQKAH"

//var Address = "TVWZVZZLWSMLXYTFQNVQSAGCQLRRCUXMUDDQWJILNQGOIFKMA9PKBRKORIWOOF9WQLJWGVGTWUXPNNKNYSRBAWUWQC" //"TVWZVZZLWSMLXYTFQNVQSAGCQLRRCUXMUDDQWJILNQGOIFKMA9PKBRKORIWOOF9WQLJWGVGTWUXPNNKNYSRBAWUWQC"
var Address = "HZIQ9FHDEQEQLMKFVXLMLEWXBUZQORXGWIWFMSOCWA9KMIXRJ9HTTUPTQMUDFWBCUVUZSACHECQQGPHNC"

var Provider = "https://nodes.testnet.thetangle.org:443"

var MWM int64 = 9 // In the real world set this to 14 or 15!
